apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulutbilisim
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bulutbilisim  
  template:
    metadata:
      labels:
        app: bulutbilisim
    spec:
      containers:
      - name: bulutbilisim-container
        image: mehmetemincakir/bulutbilisim:v1
        ports:
        - containerPort: 5000